// AUTO-GENERATED by scripts/generate_session_artifacts.py --product founden
// DO NOT EDIT MANUALLY. Edit apps/shared/data/founden-capabilities.json instead.

import * as z from "zod";

export interface CapabilityDef {
  name: string;
  description: string;
  method: string;
  path: string;
  inputSchema: Record<string, z.ZodType>;
}

export const CAPABILITIES: CapabilityDef[] = [
  {
    name: "build_company",
    description: "Start a Founden build from a plain-language prompt. Cost: 1 credit.",
    method: "POST",
    path: "/v1/builds",
    inputSchema: {
      prompt: z.string().describe("What to build or change, in plain language."),
      company_id: z.string().optional().describe("Target an existing company you own. Omit to use (or create) your default company."),
    },
  },
  {
    name: "get_build",
    description: "Get build status and the live preview URL. Cost: 0 credits.",
    method: "GET",
    path: "/v1/builds/{execution_id}",
    inputSchema: {
      execution_id: z.string().describe("The execution_id returned by build_company."),
    },
  },
  {
    name: "message_build",
    description: "Send a follow-up instruction to a running build. Cost: 0 credits.",
    method: "POST",
    path: "/v1/builds/{execution_id}/message",
    inputSchema: {
      execution_id: z.string().describe("The execution_id returned by build_company."),
      prompt: z.string().describe("Follow-up instruction for the running build agent."),
    },
  },
  {
    name: "stop_build",
    description: "Stop a running build. Cost: 0 credits.",
    method: "POST",
    path: "/v1/builds/{execution_id}/stop",
    inputSchema: {
      execution_id: z.string().describe("The execution_id returned by build_company."),
    },
  },
];
